### ISSUE TITLE
Issues related to running the code.

### ISSUE THREAD

**Issue by Randheer91** [noagarcia/keras_rmac#6]
I ran your code in my local system and I got the following error, 
`Traceback (most recent call last):
  File "rmac.py", line 92, in <module>
    model = rmac((x.shape[1], x.shape[2], x.shape[3]), len(regions))
  File "rmac.py", line 34, in rmac
    vgg16_model = VGG16(utils.DATA_DIR + utils.WEIGHTS_FILE, input_shape)
  File "/home/randheer/keras_rmac/vgg16.py", line 61, in VGG16
    model.load_weights(weights_path)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1762, in assign
    name=name)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/randheer/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))`
**ValueError: Dimension 0 in both shapes must be equal, but are 344064 and 25088. Shapes are [344064,4096] and [25088,4096]. for 'Assign_26' (op: 'Assign') with input shapes: [344064,4096], [25088,4096].**

My directory looks like this:
->data
---->vgg_weights.h5
---->sample.jpg
->RoiPooling.py
->rmac.py
->vgg16.py
->get_regions.py
->utils.py

Can you address this problem? 
Waiting for a reply

**Comment by djongpo** [comment]
I also ran into the same error while running your code. As said by @Randheer91 can anyone please solve the issue? @noagarcia

**Comment by noagarcia** [comment]
Are you using theano backend?

**Comment by kushal-chakraborty** [comment]
No, @noagarcia I'm using Tensorflow backend

**Comment by djongpo** [comment]
The code is running on keras in Tensorflow backend.

**Comment by noagarcia** [comment]
That might be the problem. Try running the code with the same libraries as in the Readme file.
